backend:
  name: github
  branch: master
  repo: JacobPfeifer/wichita-ultimate

# Comment below to disable drafts
publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name", "github"]
        valueField: "name"
      - { label: "Header Image", name: "header-img", widget: "image" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: True
    slug: "{{fields.fields.name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  # Authors
  - name: "authors"
    label: "Author"
    folder: "authors"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "GitHub", name: "github", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}
  # Pickup Games
  - name: "pickup-games"
    label: "Pickup"
    folder: "pickup"
    create: true
    slug: "{{fields.title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Mainainer's Name", name: "name", widget: "string"}
      - {label: "Maintainter's Email", name: "email", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "When", name: "frequency", widget: "string"}
      - {label: "Online Discussion", name: "discussion", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
  # Leagues

   